### ISSUE TITLE
Does not support Python < 3.10

### ISSUE THREAD

**Issue by dilex42** [guilatrova/gracy#2]
Only supports py>=3.10 instead of stated 3.8. Either description is wrong or config file.

**Comment by guilatrova** [comment]
Thanks for reporting!

The config was wrong. I still need to test it more, but it should be working with Python >=3.8.

The new 1.6.1 version should have it fixed :+1:

**Comment by dilex42** [comment]
Unfortunately it doesn't work, as the code relies heavily on `|` in annotations. Thanks for trying
