### ISSUE TITLE
Namespacing API functional areas?

### ISSUE THREAD

**Issue by BenGable** [guilatrova/gracy#26]
I'm looking at using Gracy for an API with a lot of different endpoints spread over 7 or 8 different functional areas (for example: users, requests, acquisitions, etc). Using a flat hierarchy for the API client would be very user-unfriendly (just too many functions with overlapping names), so I'd like to namespace them like so:

MyAPI.users.get_user()
MyAPI.users.requests.get_user_requests()
MyAPI.acquisitions.create_order()

The idea would be that namespaces would be nested several deep and would all share the same top-level config. I can't see any obvious way to achieve this with Gracy given how config works - is there anything you would suggest/is there any scope for implementing this functionality?

Thanks in advance, and props for the great project!

**Comment by guilatrova** [comment]
Is this API public so I can take a look, and possibly write a sample with 2 namespaces?

**Comment by BenGable** [comment]
The API is documented [here](https://developers.exlibrisgroup.com/alma/apis/). You can see there are a number of top-level functional areas, then logical groupings within each. To take a concrete example, I'd like to see:

Alma.bibs.get_bib
Alma.bibs.requests.get_requests
Alma.bibs.loans.get_loans

Alma.users.get_user
Alma.users.requests.get_requests
Alma.users.loans.get_loans

As you can see there are a large number of endpoints with closely overlapping but distinct functionality, so a huge long list of functions with slightly different verbose names is not great to work with. This is probably quite an extreme example, but I think this would be nice to have for less complex APIs too.

**Comment by guilatrova** [comment]
Thank you for sharing. I believe it's doable, let me create some sort of sample code over the week.
It will be good as a showcase :+1:

**Comment by guilatrova** [comment]
I decided to create a clean wrapper for that: https://github.com/guilatrova/gracy/pull/27 

I need to test it a bit more before releasing though, but expect something to be used as:

```py
from __future__ import annotations

import asyncio
import typing as t
from http import HTTPStatus

from gracy import (
    BaseEndpoint,
    Gracy,
    GracyConfig,
    GracyNamespace,
    LogEvent,
    LogLevel,
    parsed_response,
)
from gracy.replays.storages._base import GracyReplay
from rich import print

RESP_TYPE = t.Union[t.Dict[str, t.Any], None]


class PokeApiEndpoint(BaseEndpoint):
    BERRY = "/berry/{KEY}"
    BERRY_FLAVOR = "/berry-flavor/{KEY}"
    BERRY_FIRMNESS = "/berry-firmness/{KEY}"

    POKEMON = "/pokemon/{KEY}"
    POKEMON_COLOR = "/pokemon-color/{KEY}"
    POKEMON_FORM = "/pokemon-form/{KEY}"


class PokeApiBerryNamespace(GracyNamespace[PokeApiEndpoint]):
    @parsed_response(RESP_TYPE)
    async def get_this(self, name_or_id: t.Union[str, int]):
        return await self.get(PokeApiEndpoint.BERRY, dict(KEY=str(name_or_id)))

    @parsed_response(RESP_TYPE)
    async def get_flavor(self, name_or_id: t.Union[str, int]):
        return await self.get(PokeApiEndpoint.BERRY_FLAVOR, dict(KEY=str(name_or_id)))

    @parsed_response(RESP_TYPE)
    async def get_firmness(self, name_or_id: t.Union[str, int]):
        return await self.get(PokeApiEndpoint.BERRY_FIRMNESS, dict(KEY=str(name_or_id)))


class PokeApiPokemonNamespace(GracyNamespace[PokeApiEndpoint]):
    @parsed_response(RESP_TYPE)
    async def get_this(self, name_or_id: t.Union[str, int]):
        return await self.get(PokeApiEndpoint.POKEMON, dict(KEY=str(name_or_id)))

    @parsed_response(RESP_TYPE)
    async def get_color(self, name_or_id: t.Union[str, int]):
        return await self.get(PokeApiEndpoint.POKEMON_COLOR, dict(KEY=str(name_or_id)))

    @parsed_response(RESP_TYPE)
    async def get_form(self, name_or_id: t.Union[str, int]):
        return await self.get(PokeApiEndpoint.POKEMON_FORM, dict(KEY=str(name_or_id)))


class PokeApi(Gracy[PokeApiEndpoint]):
    class Config:  # type: ignore
        BASE_URL = "https://pokeapi.co/api/v2/"
        REQUEST_TIMEOUT = 5.0
        SETTINGS = GracyConfig(
            parser={
                HTTPStatus.OK: lambda resp: resp.json(),
                HTTPStatus.NOT_FOUND: None,
            },
            allowed_status_code=HTTPStatus.NOT_FOUND,
            log_errors=LogEvent(LogLevel.ERROR),
        )

    def __init__(self, replay: GracyReplay | None = None, DEBUG_ENABLED: bool = False, **kwargs: t.Any) -> None:
        super().__init__(replay, DEBUG_ENABLED, **kwargs)

        self._berry_ns = PokeApiBerryNamespace(self)
        self._pokemon_ns = PokeApiPokemonNamespace(self)

    @property
    def berry(self):
        return self._berry_ns

    @property
    def pokemon(self):
        return self._pokemon_ns


async def main():
    api = PokeApi()

    berry = api.berry.get_this("cheri")
    berry_flavor = api.berry.get_flavor("spicy")
    pikachu = api.pokemon.get_this("pikachu")
    black = api.pokemon.get_color("black")

    results = await asyncio.gather(berry, berry_flavor, pikachu, black)

    for content in results:
        print(content)

    api.report_status("rich")


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by guilatrova** [comment]
[Gracy v1.28.1](https://pypi.org/project/gracy/1.28.1/) supports this now :)

**Comment by BenGable** [comment]
This is fantastic, thank you very much! Initial testing suggests this does exactly what I wanted.

**Comment by guilatrova** [comment]
@BenGable Thank you for your contribution :heart: . Let me know how Gracy works for you!
