### ISSUE TITLE
Throttling limit per second doesn't recognize values smaller than 1 second. Can you force a longer pause?

### ISSUE THREAD

**Issue by mborus** [guilatrova/gracy#5]
Hi, love your project and had to try it out immediately.

I ran into a showstopper right away.

For throttling I need to throttle requests to make sure there's several seconds between each,

Real world intervals are: 
- 1 every 61 seconds (if you call more than once a minute you get valid answers but they are empty)
- 1 every 15 seconds (where I have a daily call limit to get position data and use up all tokens if I ask more)
- 1 every 5 seconds (when web scraping to make sure I don't take up too many ressources)

I tried to enforce the 5 second rule this.

            throttling=GracefulThrottle(
                rules=ThrottleRule(url_regex=r".*", limit_per_second = 0.2),
            )

If I do it like this, I get no throttling at all.

It there a way of doing this or to define a minimum wait time after each request (which would also apply to retries)?

**Comment by guilatrova** [comment]
That's a valid use case. I'll implement something over the weekend to improve this logic.

I'll allow the rule to define X requests per Y seconds/minutes/hours.

It already works with retries, so it will suit your needs. 😁

Expect something over the next days.

**Comment by mborus** [comment]
Thanks. I'm looking forward to testing this when it becomes available and give feedback if I run into problems.
