### ISSUE TITLE
How to trigger a retry from the parser based on the reply content.

### ISSUE THREAD

**Issue by mborus** [guilatrova/gracy#7]
Hi,

in the GracyConfig I can define my own parser.

Is there a way from my own parsing code to trigger a retry?

    def my_parser(r):
        try:
            return r.json() 
        except Exception:
            # trigger retry:
            raise MyException("Invalid JSON received")

    class Config:
      SETTINGS = GracyConfig(
        ...,
        allowed_status_code=HTTPStatusCode.NOT_FOUND,
        parser={
          "default": my_parser
        }
      )

Use case: I am querying a borky API that sometime returns incomplete / broken results and
sometimes returns a HTML error page instead of the requested json result. 

I'd have to write my own parser that decides if a retry should be made.
Exiting this with by raising an Error that triggers a retry would be a clean way
of doing this

---

Some more on this:

I'm hunting a case where the API delivers a code 504 HTML Gateway timeout message that
crashes the retries consistently with a GracyParseFailed after the first retry. 
Haven't been able to create a reproducable example yet, because in theory 504 
responses shouldn't get parsed - and when I built a local api that returns 504's 
Gracy works fine catching those.

So while I look for this, I'm trying to catch all Gracy Exceptions:

I looked at the exections and found that
    class GracyParseFailed(Exception):
is not a "GracyException"

What's the decision about that? 
(You wrote a great blog article on proper exception design so there's probably me missing something here)

In my case using Gracy I'd watch a to try/catch all GracyExceptions as a safety net, 
It would be useful to just need to try to catch GracyException and maybe even have a GracyTypeError Exception (that becomes a Gracy Exception) because currently the code may raise generic TypeErrors at some point.

**Comment by guilatrova** [comment]
After reading and considering it makes me think I should create "validators" to support custom rules for requests/responses.

I'll make sure to resolve this over next days/week :)

**Comment by guilatrova** [comment]
Don't use parsers for this. 

You can achieve that by:

```py
from gracy import GracefulValidator
import httpx

class JSONValidator(GracefulValidator):  # 👈 Inherit from GracefulValidator
    def check(self, response: httpx.Response) -> None:
        try:
           response.json()
        except Exception:
           raise MyException("Invalid JSON received") # 👈 Define an exception you can capture for retry

class Config:
  SETTINGS = GracyConfig(
    ...,
    allowed_status_code=HTTPStatusCode.NOT_FOUND,
    validators=JSONValidator(),
    retry=GracefulRetry(retry_on=MyException, ...),  # 👈 Specify you want to retry on this exception
    parser={
      "default": lambda r: r.json() # 👈 Won't be triggered if validator fails/retry exhausts
    }
  )
```
